version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            cd udagram && npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            cd udagram && npm run backend:install
      - run:
          name: Front-End Build
          command: |
            cd udagram && npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            cd udagram && npm run backend:build
      - run:
          name: Deploy App
          command: |
            cd udagram && npm run frontend:deploy
